### ISSUE TITLE
Optimizer not making accurate predictions.

### ISSUE THREAD

**Issue by CoryMcCartan** [robototes/ReinforcementLearning#24]

**Comment by maxnotarangelo** [comment]
optimizes for 1-2 cycles, then worsens and is held constant
@CoryMcCartan

**Comment by CoryMcCartan** [comment]
only happens on variable index 0.

for some reason function evaluation thinks that worse values are better (either that or incorrectly moves the pattern) and then gets stuck, continually scaling down the search range and not moving

**Comment by CoryMcCartan** [comment]
error occurs on first move of the pattern

**Comment by CoryMcCartan** [comment]
funny part is that one `=` sign was all it took.
